### ISSUE TITLE
Some incoming trades don't display currency icons

### ISSUE THREAD

**Issue by bhnn** [C1rdec/Poe-Lurker#296]
Incoming trades, such as my chaos for their chances/chromes/..., do not show an image of the currency they want. Looks like the only available images are chaos and exalts.

![image](https://user-images.githubusercontent.com/13474968/140628789-db9c91bd-3e8f-4c5e-a105-a2871ebc3d79.png)

The prices I selected are from the game's dropdown menu of available options, not one of the [other available tags](https://currency.poe.trade/tags). Some examples of tags that successfully display an image:

- `~price 1 exalted`
- `~price 1 chaos`

Malfunctioning example from the screenshot above:

- `~price 55 chance`

**Comment by C1rdec** [comment]
What's your resolution?

**Comment by bhnn** [comment]
1920x1080 in Windowed Fullscreen mode using the Vulkan renderer at the moment.

**Comment by bhnn** [comment]
So far I can confirm that breach splinters, chances, scours, fuses, sextants, orbs of unmaking and chisels are not displaying and image.

**Comment by C1rdec** [comment]
![image](https://user-images.githubusercontent.com/5436436/140766382-63fd2046-6384-4e90-aafa-f2689f62f8a7.png)

I will add 'Scouring' and 'Chance' but regarding other currencies I dont see my self implementing those since their are not commonly used for trade

**Comment by bhnn** [comment]
Do you edit the images in any way or would you just need a mapping of name of currency : link to image to display all the remaining currencies?

**Comment by C1rdec** [comment]
No there's work in the parser

**Comment by bhnn** [comment]
I noticed another issue with the missing currencies. Placeholders like {Price} don't work for trades where the incoming currency icon is missing.

**Comment by lobo235** [comment]
I have noticed the same thing with the missing icon and {Price} placeholder not being replaced for Blessed Orbs. I have a tab where I sell things for 3 Blessed Orbs and the icon never shows up for those trades and the 'Still Interested?' message I send that has the {Price} placeholder does not get populated. Using Windowed Fullscreen, DX11, 1440x900 resolution.

**Comment by C1rdec** [comment]
Fixed in 1.16.0

**Comment by lobo235** [comment]
In 1.16.3 blessed orbs still don't work.

**Comment by C1rdec** [comment]
https://github.com/C1rdec/Poe-Lurker/issues/296#issuecomment-963252835

**Comment by RhapsodySL** [comment]
Re-opening as this issue still occurs with Awakened Sextants: 
![image](https://user-images.githubusercontent.com/8369578/173502588-e0e96789-a380-42e8-93f7-7661b83177e6.png)

In regards to https://github.com/C1rdec/Poe-Lurker/issues/296#issuecomment-963252835, Awakened Sextants are used commonly as the type of currency used to trade for Charged Compasses, as it eases the burden on sextant rollers. Look up almost any sextant and you'll see that a vast majority of them use Awakened Sextants.
